apiVersion: v1
kind: Secret
metadata:
  name: cosmosdb-secret
type: Opaque
data:
  uri: base64-your-cosmosdb-uri

---
apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
type: Opaque
data:
  key: base64-your-openai-key
