apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-admin
  template:
    metadata:
      labels:
        app: django-admin
    spec:
      containers:
      - name: django
        image: yourdockerhubuser/django-admin:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: cosmosdb-secret
              key: uri
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: django-admin
